### ISSUE TITLE
Ive tried it but it doesnt work

### ISSUE THREAD

**Issue by Hsys7272** [ShrinathN/KissAnimeRipper#2]
Tried two animes with this. It just stops on the 1st episode

**Comment by ShrinathN** [comment]
Yes, it is defunct now, I shall update the project page.

Kissanime removed the mediafire download links, so there's no way to easily download except downloading the video stream.

You can set up and use this tool, if you wish, its much better than mine
https://github.com/vn-ki/anime-downloader
